# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Foxling's blog
email: i.foxling@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  凌晔，一名 iOS 工程师，坐标上海，从2012起一直在蝉小队工作。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://foxling.github.io" # the base hostname & protocol for your site
twitter_username: lingye
github_username:  foxling

# Build settings
markdown: kramdown
